baseURL: 'https://wayism.github.io/caminismo'  # Will change to caminismo.com later
languageCode: es-MX
title: 'Caminismo - elCAMINO'
defaultContentLanguage: es

# Custom parameters for Caminismo site
params:
  description: "La filosofía espiritual Wayist en español - Descubra el propósito de la vida y el camino hacia la transformación espiritual"
  keywords: [caminismo, wayismo, espiritualidad, filosofía, meditación, dharma, karma, camino espiritual]
  author: "Comunidad Caminista"

# Menu configuration
menu:
  main:
    - identifier: inicio
      name: Inicio
      url: /
      weight: 10
    - identifier: acerca
      name: Acerca de Caminismo
      url: /acerca/
      weight: 20
    - identifier: ensenanza
      name: Enseñanza Principal
      url: /ensenanza/
      weight: 30
    - identifier: libros
      name: Libros
      url: /libros/
      weight: 40
    - identifier: comunidad
      name: Comunidad
      url: https://wayist.life
      weight: 50

# Build settings
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false
    anchorLineNos: true
    codeFences: true
    guessSyntax: true
    lineNos: true
    style: github

# Output formats
outputs:
  home:
    - HTML
    - RSS
    - JSON